/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package webhook.app;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;

import java.awt.*;

@SpringBootApplication
public class App {
	public static void main (String[] args) {
		System.out.println (new App ().getGreeting ());

		var ctx = new SpringApplicationBuilder (App.class).headless (false).run (args);

		EventQueue.invokeLater (() -> {

			var ex = ctx.getBean (App.class);
		});
	}

	public String getGreeting () {
		return "Hello World!";
	}
}
